### ISSUE TITLE
C2 voltage rating

### ISSUE THREAD

**Issue by cednik** [RoboticsBrno/RB0005-UniversalStepDown#1]
C2 should be at least for 25 V.
I suggest 100 nF @ 50 V 0603 [C14663](https://lcsc.com/product-detail/Multilayer-Ceramic-Capacitors-MLCC-SMD-SMT_100nF-104-10-50V_C14663.html/?href=jlc-SMT).

**Comment by yaqwsx** [comment]
Resolved in 60372b8f240a20923353d0b3388f130479edcc53
