### ISSUE TITLE
Enable pull-p value

### ISSUE THREAD

**Issue by cednik** [RoboticsBrno/RB0005-UniversalStepDown#2]
I suggest use 1M resistor [C26083](https://lcsc.com/product-detail/Chip-Resistor-Surface-Mount_Uniroyal-Elec-0402WGF1004TCE_C26083.html/?href=jlc-SMT).

**Comment by yaqwsx** [comment]
Resolved in 60372b8f240a20923353d0b3388f130479edcc53
