### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by PexMor** [RoboticsBrno/RB0005-UniversalStepDown#4]
Hello Honza,

I just have spotted that the link to 5V v2 eval is wrong:

now it is:
https://roboticsbrno.github.io/RB0005-UniversalStepDown/eval5v/eval5v_v2

but this actually work:
https://roboticsbrno.github.io/RB0005-UniversalStepDown/eval5v_v2

Can you have a look and eventually fix it :-)
Petr

**Comment by yaqwsx** [comment]
Thank you for noting, Peter! I fixed the link in 6bc64e2.
