### ISSUE TITLE
Query regarding Cin caps

### ISSUE THREAD

**Issue by solarmon** [RoboticsBrno/RB0005-UniversalStepDown#5]
Hi.

In the 12v to 5V v2 design, there are 3 x 22uF input caps.

But in the SY8105 data sheet:

https://datasheet.lcsc.com/szlcsc/1810010130_Silergy-Corp-SY8105ADC_C178247.pdf?fbclid=IwAR0DE38_i6aVWT9JrmcbFluUpxaj8PLlHQslrLvlyKU2XdDWP8QoU_eVYwc

The application diagram only shows 1 x 10uF cap. Although, further down in the notes for CIN, it also suggests having a 100nF cap in parallel with the 10uF cap.

Can you explain the benefits of this design with three 22uF input caps versus what is recommended in the SY8105 data sheet.

**Comment by yaqwsx** [comment]
Usage for 3x 22uF caps basically came up from our experiments with the chip - it slightly better reacts to pulse loads compared to the value in the datasheet (especially for RC servos). Also, the step-down is designed for hacky/dirty usage where the users often use long input leads and do not supply the stepdown with an additional electrolytic capacitor.

The 100 nF capacitor is missing as it makes no difference in our experience; often a single large ceramic capacitor performs similarly; you can read more about it in [this thread](https://twitter.com/BenKrasnow/status/1084196370267856896) with Ben Krasnow from Applied science - there are some interesting papers and slides listed.

**Comment by solarmon** [comment]
Thanks for the quick response.

I'm looking to use the circuit design to power 5V floppy drives, so the use case is not the same compared to the intended use. Although, the the floppy drives do have a step motor in them.

I suspect I could get away with using just a single 10uF cap, as per the data sheet, for my use case.

**Comment by yaqwsx** [comment]
I think a 10uF cap should work fine for you.
